service:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: omega
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
      volumes:
        - db:/data/postgres
      ports:
        - "5332:5432"
      networks:
        -db
      restart: unless-stopped
